import io

from docx import Document
from supabase import acreate_client

from app.core.config import settings

_DOCX_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

_client = None


async def _get_client():
    global _client
    if _client is None:
        _client = await acreate_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_ROLE_KEY)
    return _client


def build_docx(tasks: list[dict], title: str = "AAF Study Plan") -> bytes:
    doc = Document()
    doc.add_heading(title, level=1)

    table = doc.add_table(rows=1, cols=3)
    table.style = "Light Grid Accent 1"
    header_cells = table.rows[0].cells
    header_cells[0].text, header_cells[1].text, header_cells[2].text = "Task", "Time", "Details"

    for task in tasks:
        cells = table.add_row().cells
        cells[0].text = task["name"]
        cells[1].text = task["time_hint"]
        cells[2].text = task["details"]

    footer = doc.add_paragraph()
    footer.add_run("Generated by AAF (Anteater Acing the Future)").italic = True

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


async def upload_and_sign(object_path: str, file_bytes: bytes, expires_in: int = 600) -> str:
    client = await _get_client()
    bucket = client.storage.from_(settings.SUPABASE_STORAGE_BUCKET)
    await bucket.upload(
        object_path,
        file_bytes,
        file_options={"content-type": _DOCX_CONTENT_TYPE, "upsert": "true"},
    )
    signed = await bucket.create_signed_url(object_path, expires_in)
    return signed["signedURL"]
